apiVersion: v1
kind: ConfigMap
metadata:
  # Tên của ConfigMap, khớp với 'configmap_name'
  name: client-pod-template
  namespace: split-learning
data:
  template.yaml: |
    containers:
    - name: nginx      
      image: nginx:1.25         
      ports:
      - containerPort: 80        
        protocol: TCP
    restartPolicy: Always    