apiVersion: v1
kind: ServiceAccount
metadata:
  name: split-learning-controller
  namespace: split-learning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: split-learning-controller-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["splitlearning.io"]
  resources: ["clientlayer1s"]
  verbs: ["create", "get", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: split-learning-controller-binding
subjects:
- kind: ServiceAccount
  name: split-learning-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: split-learning-controller-role
  apiGroup: rbac.authorization.k8s.io