version: '3'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ${PWD}/rabbitmq_config/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/rabbitmq_config/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq1-data:/var/lib/rabbitmq/
      - rabbitmq1-logs:/var/log/rabbitmq
      - ./rabbitmq_config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq_config/limits.conf:/etc/security/limits.conf
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - SL-network

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    container_name: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ${PWD}/rabbitmq_config/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/rabbitmq_config/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq2-data:/var/lib/rabbitmq/
      - rabbitmq2-logs:/var/log/rabbitmq
      - ./rabbitmq_config/limits.conf:/etc/security/limits.conf
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - SL-network

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    container_name: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ${PWD}/rabbitmq_config/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/rabbitmq_config/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq3-data:/var/lib/rabbitmq/
      - rabbitmq3-logs:/var/log/rabbitmq
      - ./rabbitmq_config/limits.conf:/etc/security/limits.conf
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - SL-network

  haproxy:
    image: haproxy:1.7
    container_name: rabbitmq_proxy
    volumes:
      - ${PWD}/rabbitmq_config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - SL-network

  server:
    image: server  # Tên image local của bạn
    container_name: server
    depends_on:
      - haproxy    
    volumes:
      - ./config.yaml:/app/config.yaml  # Mount file cấu hình
      - ./server_result/server.log:/app/app.log
      - ./server_result/VGG16.pth:/app/VGG16.pth
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 15 && python server.py"]

  client11:
    image: client
    container_name: client1-1
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml  
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 1 --device cpu"]
  client12:
    image: client
    container_name: client1-2
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml  
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 1 --device cpu"]
  client13:
    image: client
    container_name: client1-3
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml  
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 1 --device cpu"]
  client21:
    image: client
    container_name: client2-1
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml  
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 2 --device cpu"]

  client22:
    image: client
    container_name: client2-2
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml  
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 2 --device cpu"]

  client3:
    image: client
    container_name: client3
    depends_on:
      - server
    volumes:
      - ./config.yaml:/app/config.yaml  
    networks:
      - SL-network
    command: ["sh", "-c", "sleep 20 && python client.py --layer_id 3 --device cpu"]

volumes:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs:

networks:
  SL-network:
    driver: bridge
