apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: minhbui1/server
          command: ["sh", "-c", "sleep 15 && python server.py"]
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: server-result
              mountPath: /app/server_result
      volumes:
        - name: config-volume
          configMap:
            name: app-config
        - name: server-result
          persistentVolumeClaim:
            claimName: server-result-pvc
