apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-log-pvc
  namespace: split-learning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  volumeName: server-log-pv