apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-log-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/k8s/data/serverlog"